# Generated by Django 4.2.14 on 2024-10-06 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_comment_options'),
        ('users', '0005_customuser_first_name_en_customuser_first_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('less_recommend', models.ManyToManyField(blank=True, related_name='less_recommend', to='articles.article')),
                ('more_recommend', models.ManyToManyField(blank=True, related_name='more_recommend', to='articles.article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
