# Generated by Django 4.2.14 on 2024-10-07 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_is_recommend'),
        ('users', '0010_alter_recommendation_less_recommend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='less_recommend',
            field=models.ManyToManyField(blank=True, related_name='less_recommended_by_users', to='articles.topic'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='more_recommend',
            field=models.ManyToManyField(blank=True, related_name='more_recommended_by_users', to='articles.topic'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
