# Generated by Django 4.2.14 on 2024-10-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_recommendation_less_recommend_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
