# Generated by Django 4.2.14 on 2024-10-07 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_is_recommend'),
        ('users', '0012_delete_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('less_recommend', models.ManyToManyField(blank=True, related_name='less_recommended_by_users', to='articles.topic')),
                ('more_recommend', models.ManyToManyField(blank=True, related_name='more_recommended_by_users', to='articles.topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendation',
                'ordering': ['-created_at'],
            },
        ),
    ]
