# Generated by Django 4.2.14 on 2024-10-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_readinghistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinghistory',
            options={'verbose_name': 'Reading history', 'verbose_name_plural': 'Reading Histories'},
        ),
        migrations.AlterModelTable(
            name='readinghistory',
            table='reading_history',
        ),
    ]
