# Generated by Django 4.2.14 on 2024-10-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
