# Generated by Django 4.2.14 on 2024-10-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_notification_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='author',
            new_name='user',
        ),
    ]
