# Generated by Django 4.2.14 on 2024-10-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_notification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
