# Generated by Django 4.2.14 on 2024-09-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_clap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reads_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
