# Generated by Django 4.2.14 on 2024-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_recommend',
            field=models.BooleanField(default=False),
        ),
    ]
