# Generated by Django 4.2.14 on 2024-10-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_is_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('publish', 'Publish'), ('trash', 'Trash')], default='pending', max_length=20),
        ),
    ]
