# Generated by Django 4.2.14 on 2024-10-12 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='clap',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_article', to='articles.article'),
        ),
    ]
