# Generated by Django 4.2.14 on 2024-10-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_clap_count_alter_favorite_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clap',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
