# Generated by Django 4.2.14 on 2024-10-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('publish', 'Publish'), ('trash', 'Trash'), ('archive', 'Archive')], default='pending', max_length=20),
        ),
    ]
