# Generated by Django 4.2.14 on 2024-10-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_pin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
