# Generated by Django 4.2.14 on 2024-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_report_report_unique_fields_user_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
